serverPort: 8500

# 数据库配置
#	password := "cyc_db123"
#	password := "Longyue.db.2023"
database:
  host: 127.0.0.1
  port: 3306
  dbname: yang_server
  username: root
  password: root
  myconfig: charset=utf8&parseTime=True